### ISSUE TITLE
make.shared

### ISSUE THREAD

**Issue by LeeJH5120** [mothur/mothur.github.io#100]
shared file and count_table file
have the same classification ID, but different counts.

if 
read count_table | grep M06221_430_000000000-KWB4V_1_2109_14089_10175 
M06221_430_000000000-KWB4V_1_2109_14089_10175 691
(M~:ID; 691:count)

read list file | grep M06221_430_000000000-KWB4V_1_2109_14089_10175
Otu00001 M06221_430_000000000-KWB4V_1_2109_14089_10175

read shared file | grep M06221_430_000000000-KWB4V_1_2109_14089_10175
Otu00001 0

This is a critical problem for downstream analysis.

**Comment by LeeJH5120** [comment]
Solved.

After creating a shard + list with count_table, using the created list
If you do make.shared(list, count_table) again, it works normally.

I wonder if there is any reason to process it one more time.

**Comment by pschloss** [comment]
Glad you got it solved. In the future, these types of questions should be posted at forum.mothur.org
