### ISSUE TITLE
Question on: Greengenes-formatted databases

### ISSUE THREAD

**Issue by cgini31** [mothur/mothur.github.io#103]
Hello!
Greengenes2 is out there! I was wondering if you are preparing a formatted-database to be used on Mothur! Thanks in advance.

Here the references:
paper: https://www.biorxiv.org/content/10.1101/2022.12.19.520774v1
server: http://ftp.microbio.me/greengenes_release/

**Comment by pschloss** [comment]
Do you have a link to the paper describing these releases? The path you
provided is an absolute path to your computer.

Thanks,
Pat
