### ISSUE TITLE
Customized 5.8S-ITS2 sequence for trimming silva seed reference.

### ISSUE THREAD

**Issue by zhinew15** [mothur/mothur.github.io#106]
Hi all,

I am having trouble finding the sequence of 5.8S-ITS2 to trim the silva.seed_v132.align database. I found the primers my project used from Taylor et al., 2016 (doi:10.1128/AEM.02576-16), blasted the primer, but it didn't work. What else should I do?

**Comment by pschloss** [comment]
The silva database only has 16S and 18S rRNA gene sequences. There are no
ITS sequences in there.

Pat

**Comment by zhinew15** [comment]
Oh, thanks Pat!
