### ISSUE TITLE
Question on: About ASV command

### ISSUE THREAD

**Issue by NazishAijaz** [mothur/mothur.github.io#109]
I have claasify otu file but now i need to run asv command but that command need asv list so how can i use that list because in mothur i dont have that list so now how can i run that command to get asv from classify otus please help me regarding this , (rpoB.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.pick.subsample.fn.unique_list.list) that list i have so using this how can i run asv command.

**Comment by pschloss** [comment]
Hi - if you go through the MiSeq SOP you will see there is a [section there on ASVs](https://mothur.org/wiki/miseq_sop/#asvs). If you try that workflow and things still don't work, please ask a question along with what you've tried on the forum at forum.mothur.org.
