### ISSUE TITLE
Question on: mothur website

### ISSUE THREAD

**Issue by Mohamed-S-AboHoussien** [mothur/mothur.github.io#113]
hello all please need a help with this error
mothur > chimera.vsearch(vsearch=/usr/bin/vsearch.2.17.1, fasta=stability.trim.contigs.good.unique.good.filter.unique.precluster.fasta, count=stability.trim.contigs.good.unique.good.filter.unique.precluster.count_table)

Using 8 processors.
Unable to open /usr/bin/vsearch.2.17.1. Trying mothur's executable directory vsearch.2.17.1.
Unable to open vsearch.2.17.1.
Unable to open /usr/bin/vsearch.2.17.1
not open file does not exist or cannot be opened, ignoring.
Unable to open vsearch. Trying mothur's executable directory vsearch.
Unable to open vsearch.
vsearch file does not exist. Checking path... 
[ERROR]: vsearch file does not exist. mothur requires the vsearch executable.
[ERROR]: did not complete chimera.vsearch.

mothur > chimera.vsearch(fasta=stability.trim.contigs.good.unique.good.filter.unique.precluster.fasta, count=stability.trim.contigs.good.unique.good.filter.unique.precluster.count_table, dereplicate=t)

Using 8 processors.
Unable to open vsearch. Trying mothur's executable directory vsearch.
Unable to open vsearch.
vsearch file does not exist. Checking path... 
[ERROR]: vsearch file does not exist. mothur requires the vsearch executable.
[ERROR]: did not complete chimera.vsearch.

**Comment by pschloss** [comment]
I'm not sure how you've installed mothur. vsearch should have been downloaded with mothur if you have the mac/linux versions. Regardless, you can get the version we use by getting the appropriate "tools" archives from https://github.com/mothur/mothur/releases/tag/v1.48.0 (or whatever version of mothur you are using).

In the future, these types of questions are best handled at forum.mothur.org.

Pat
