### ISSUE TITLE
Question on: alignment

### ISSUE THREAD

**Issue by JoeHansen4444** [mothur/mothur.github.io#117]
Hello. I am having some issues with aligning a portion of my sequences. They kept getting filtered out from the majority of the sequences, so I tried to analyze them separately to see what might be causing the issue. The number of bases are way too small, and that was after mothur flipped the sequences to create better alignment:

It took 483 secs to align 379524 sequences.

[WARNING]: 372581 of your sequences generated alignments that eliminated too many bases, a list is provided in /Users/joehansen/Documents/USA/MicrobiomeProject/Bioinformatics/HansenWithPrelimNewMethodV3V4/PreLim/prelim.trim.contigs.good.flip.accnos.

[NOTE]: 207099 of your sequences were reversed to produce a better alignment.

Start End NBases Ambigs Polymer NumSeqs

Minimum: 0 0 0 0 1 1

2.5%-tile: 1044 1060 3 0 1 9489

25%-tile: 43029 43116 9 0 3 94882

Median: 43059 43116 13 0 3 189763

75%-tile: 43097 43116 19 0 4 284644

97.5%-tile: 43112 43116 38 0 6 370036

Maximum: 43116 43116 457 0 8 379524

Mean: 39361 39658 18 0 3

# of unique seqs: 379524

total # of seqs: 379524

It took 50 secs to summarize 379524 sequences.

I am not sure why the alignment is so off, and would appreciate any feedback to why this may be happening.

**Comment by pschloss** [comment]
Hi - generally these questions are better posed on the forum to make them
easier for others to find. Could you possibly repost your question there?
It would be helpful to also post the output of running summary.seqs before
and after you ran `screen.seqs`. Also, what type of environment are you
sequencing?

Thanks,
Pat
