### ISSUE TITLE
Greengenes2 reference new release in 2023

### ISSUE THREAD

**Issue by hurleyLi** [mothur/mothur.github.io#118]
Hi, given the recent release of [Greengenes2](https://www.nature.com/articles/s41587-023-01845-1) database, could you please update the gg alignment / taxonomy reference based on the format compatible with Mother? I know you strongly against the usage of gg_13_8_99, but this new version has been improved, and an update will greatly benefit the community. 
Really appreciate it.
Hurley

**Comment by pschloss** [comment]
Sorry for the delay on this. Here's the [updated greengenes2 reference taxonomy](https://mothur.org/wiki/greengenes-formatted_databases%20copy/). I don't have any problems with using 13_8_99 for classification - only for alignment. For that SILVA is still the best option.
