### ISSUE TITLE
Question on: MiSeq SOP

### ISSUE THREAD

**Issue by christellesawaya** [mothur/mothur.github.io#120]
Hi, I ran the SOP on targeted V4 region of the 16S rRNA sequences. I used the latest mothur version, Silva Database v132, and RDP classifier version 18. I aligned the silva Database to the V4 region without the primers. After performing the Phylotype based analysis and opening the shared and taxonomy files, a lot of the samples show quantity 0 in archaea and bacteria, which I don't expect. 
So I am wondering if I misaligned the database, or if it's a result of bad classification.
For some reason mothur didn't save a logfile, but I have the results saved for reference.
I highly appreciate the help!

**Comment by pschloss** [comment]
Hi there - could you possibly repost your question at forum.mothur.org? If you could clarify whether you are looking at the kingdom level or genus level that would be helpful. If you've followed the SOP, there won't be any Archaea since those would have been removed in `get.linage`
