### ISSUE TITLE
Question on: mothur's wiki

### ISSUE THREAD

**Issue by Hadeel1353** [mothur/mothur.github.io#123]
remove.seqs tool in galaxy doesn`t work at all and the jobs failed every time i running the job , please help

**Comment by pschloss** [comment]
Hi - we have no involvement with galaxy so I'm not much help with
navigating their resources. If you have a question with using mothur, could
you post the command you are trying to run and the result including any
error messages to the mothur forum at forum.mothur.org?

Thanks,
Pat
