### ISSUE TITLE
Question on: make.file

### ISSUE THREAD

**Issue by 9843435131** [mothur/mothur.github.io#124]
Hi! I have issue making stability file. Because I have some FASTQ files and it consists of 001_ R1 and 001_R2. When I use the make.file I could make it.

**Comment by pschloss** [comment]
Hi - could you post your questions on how to use mothur to forum.mothur.org?
If you could include what your file looks like and any error messages you
are getting, that will help us figure out what is going wrong.

Thanks
Pat
