### ISSUE TITLE
Question on: LefSe on galxy

### ISSUE THREAD

**Issue by Cloverelf** [mothur/mothur.github.io#125]
Hi there,
 
May I know how the input data (e.g. structure and file format) for lefse should be?
I found that maybe I should use the make.lefse function first, but I also found a problem that input data format should be shared or relabund file. 

I made a text tab-delimited file according to the relabund structure but I didn't realize that how to let it be relabund file as well.

Thank you.

Clover

**Comment by pschloss** [comment]
I'd encourage you to follow along the MiSeq SOP, particularly the section on [population-level analysis](https://mothur.org/wiki/miseq_sop/#population-level-analysis). You should be using a subsampled shared file. In the future it would be helpful if you could post these types of questions to the [mothur forum](forum.mothur.org).

Thanks
Pat
