### ISSUE TITLE
Question on: get.groups

### ISSUE THREAD

**Issue by pecholleyn** [mothur/mothur.github.io#129]
Hi, the "Example Data" ZIP file, linked in the description, only contains an empty folder. I think it is not desire, right?

**Comment by pecholleyn** [comment]
The link works, and data in the ZIP can be used, however, when testing the "default settings", the `final.pick.count_table` I obtained, contains 571 unique sequences (M00967... ID) and not 569 as described on the page. I did not test the options.

**Comment by pschloss** [comment]
Thanks, that because the posted data are slightly different from what was
used to correct the text. I'll circle back at some point to correct that.
Pat
