### ISSUE TITLE
Question on: MiSeq SOP

### ISSUE THREAD

**Issue by jpanehal** [mothur/mothur.github.io#133]
Believe this is "too good" to be true. There is one too many uses of the word "good" in the file name....

mothur > filter.seqs(fasta=stability.trim.contigs.good.unique.good.align, vertical=T, trump=.)

should be ->

mothur > filter.seqs(fasta=stability.trim.contigs.good.unique.align, vertical=T, trump=.)

At least I think?!?!

**Comment by pschloss** [comment]
Thanks for asking, but it is correct as written :) The previous block has the following

```
mothur > screen.seqs(fasta=stability.trim.contigs.good.unique.align, count=stability.trim.contigs.good.count_table, start=1968, end=11550)
```

That will put the "good" in between the "unique" and "align."

Pat

**Comment by jpanehal** [comment]
Thanks Pat!

Figures I did something wrong. Guess me being right was too good to be true 😂

Have a happy Thanksgiving!

Juli

On Nov 27, 2024, at 5:03 AM, Pat Schloss ***@***.***> wrote:

﻿

Thanks for asking, but it is correct as written :) The previous block has the following

mothur > screen.seqs(fasta=stability.trim.contigs.good.unique.align, count=stability.trim.contigs.good.count_table, start=1968, end=11550)


That will put the "good" in between the "unique" and "align."

Pat

**Comment by pschloss** [comment]
No worries!
