### ISSUE TITLE
Question on: Customize your reference alignment for your favorite region

### ISSUE THREAD

**Issue by jacorvar** [mothur/mothur.github.io#27]
Is it worth/correct to remove oligos at last step (pcr.seqs)? I have a bunch of V3-V4 sequences and some of them are excluded via screen.seqs because of N's at the very end of the sequence (at the reverse primer). I'm wondering whether I should run trim.seqs (on my sequences) using an oligos file, whilst at the same time trimming the reference alignment using the oligos file too. Does it make sense?

Thanks

**Comment by pschloss** [comment]
It probably doesn't matter. The key is that the primers need to be removed from your new sequence data
