### ISSUE TITLE
Question on: classify.seqs

### ISSUE THREAD

**Issue by merryblues** [mothur/mothur.github.io#29]
what can i do to obtain the file that **reference  and taxonomy use** classify.seqs(fasta=stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.fasta, count=stability.trim.contigs.good.unique.good.filter.unique.precluster.denovo.vsearch.pick.count_table, **reference=trainset9_032012.pds.fasta, taxonomy=trainset9_032012.pds.tax, cutoff=80)**

**Comment by mothur-westcott** [comment]
You can download mothur's reference files here:

https://mothur.org/wiki/silva_reference_files/
https://mothur.org/wiki/rdp_reference_files/
https://mothur.org/wiki/greengenes-formatted_databases/

**Comment by merryblues** [comment]
hello, I downloaded "silva" but nothing says transeq or that I should put instead of transeq im really stuck in this step

**Comment by merryblues** [comment]
or what i shouul use
silva.bacteria. fasta
silva.bacteria.rdp.tax
                     rdp6.tax
silva.bacteria.silva.tax

**Comment by mothur-westcott** [comment]
The trainset files are from the RDP reference page. Mothur is designed to be flexible so that you can select the reference best for your analysis. If you are looking to follow the MiSeq_SOP, download the PDS version https://mothur.s3.us-east-2.amazonaws.com/wiki/trainset16_022016.pds.tgz.
