### ISSUE TITLE
Question on: mothur website

### ISSUE THREAD

**Issue by lauscherin** [mothur/mothur.github.io#34]
Dear mothur team,

I've a question about the (in)consistency of some results produced while going through the SOP (with own data). 
I clustered my filtered sequences into OTUs and did a taxonomic classification, which produces two files (stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.pick.opti_mcc.0.03.cons.taxonomy, stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.pick.opti_mcc.0.03.cons.tax.summary). But if I compare these results, I get big differences in the amount of hits per sample. Example:  
I select a taxonomic ID (e.g. Bifidobacterium), find all OTUs classified as Bifidobaterium and count the amount of hits within each sample.
Afterwards, I compare these amounts with the amount of hits saved in the summary-file. 
I would expect, that the numbers will be completely the same but in reality, the number of hits counted by selecting all OTUs are more comparable with the amount of hits found during one of the first steps, where not OTUs, but the sequences themselves get classified 
(stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.nr_v138.wang.pick.tax.summary).
Here is an example: 
[bifidobacterium_mothus_question.xlsx](https://github.com/mothur/mothur.github.io/files/4786183/bifidobacterium_mothus_question.xlsx)

Do you can explain me how these differences can be explained?
Many thanks in advance!
Angela

**Comment by mothur-westcott** [comment]
https://mothur.org/wiki/classify.otu/#basis

The *wang.taxonomy file contains the individual sequences classifications. 
The *wang.tax.summary file summarizes the individual sequences classifications.
The *cons.taxonomy file provides to the consensus taxonomy of each OTU based on the individual classifications.
The *cons.tax.summary file summarizes the OTU's classifications. Note: the default basis=OTU. 

The basis parameter allows you indicate what you want the summary file to represent, options are otu and sequence. Default is otu. 

For example consider the following basis=sequence could give Clostridiales 3 105 16 43 46, where 105 is the total number of sequences whose otu classified to Clostridiales. 16 is the number of sequences in the Clostridiales otus from groupA, 43 is the number of sequences in the Clostridiales otus from groupB, and 46 is the number of sequences in the Clostridiales otus from groupC. 

Now for basis=otu could give Clostridiales 3 7 6 1 2, where 7 is the number of otus that classified to Clostridiales. 6 is the number of otus classified to Clostridiales containing sequences from groupA, 1 is the number of otus classified to Clostridiales containing sequences from groupB, and 2 is the number of otus classified to Clostridiales containing sequences from groupC.
