### ISSUE TITLE
Question on: mothur website

### ISSUE THREAD

**Issue by IshtarMM** [mothur/mothur.github.io#35]
Hello,

I am running Mothur on my files:
Undetermined_S0_L001_I1_001.fastq.gz
Undetermined_S0_L001_R1_001.fastq.gz
Undetermined_S0_L001_R2_001.fastq.gz
My files are containes two different samples ( soil + plant). 
I want to run make.contigs and next steps only on the plant samples. 

I have a question here.  Can I get my plant samples information by using only plant barcodes in "oligo" file? 
Or first I have to use demultiplexing step to get my plant samples files then go to next steps?

Thank you in advance.

**Comment by mothur-westcott** [comment]
Mothur has two ways you can do this. First let's make a file file with your dataset's files.

stability.file: - (forwardFastq reverseFastq forwardIndex NoReverseIndex)
Undetermined_S0_L001_R1_001.fastq.gz Undetermined_S0_L001_R2_001.fastq.gz Undetermined_S0_L001_I1_001.fastq.gz  NONE

1. Run make.contigs with the full oligos file and then select the plant samples. (Recommended option)

mothur > make.contigs(file=stability.file, oligos=yourFullOligosFile, bdiffs=1, pdiffs=2) - assemble reads, create group file with reads assigned to samples

mothur > remove.groups(fasta=current, group=current, groups=NameOfSoilSample) - remove soil reads from dataset

2. Alternatively you can ignore the soil barcodes in the oligos file. To do so comment out the soil barcodes from the oligos file and run make.contigs. By adding a '#' to the beginning of the line in your oligos file mothur will ignore the line.

mothur > make.contigs(file=stability.file, oligos=yourFullOligosFile, bdiffs=1, pdiffs=2) - assemble reads, create group file with reads assigned to samples. All soil reads will be scrapped.

**Comment by pschloss** [comment]
Hi - would it be possible for you to ask this over on the forum at http://forum.mothur.org? <http://forum.mothur.org/?>

Thanks
Pat
