### ISSUE TITLE
Question on: remove.otus - groups option not valid

### ISSUE THREAD

**Issue by miragr** [mothur/mothur.github.io#39]
I am trying to run this with shared and groups options, but it complains that groups is not a valid parameter. So I am trying to remove all OTUs (ASVs) that are present in negative control - is this the way to do that or is there some better way? I also would like to update count and list files so that I could use classify.otu with updated files.

**Comment by mothur-westcott** [comment]
To remove negative control sample from a shared file, try this:

mothur > remove.groups(shared=yourSharedFile, groups=negativeControlSampleName) 

To remove negative control from all files, try this:

mothur > remove.groups(shared=yourSharedFile, list=yourListFile, count=yourCountFile, taxonomy=yourTaxonomyFile, groups=negativeControlSampleName)

**Comment by miragr** [comment]
Thank you for the quick response! I don't want to remove the control sample from the data but I want to remove all those OTUs that are found in control, from all the other samples. There is a following line in the wiki-page of remove.otus command:
remove.otus(shared=abrecovery.an.shared, groups=B)
I assumed that this would do what I want but when I tried a similar command, mothur complained that groups-argument is not valid.

**Comment by mothur-westcott** [comment]
I'm sorry for the confusion, the wiki page is a bit out of date. The groups options is not available for remove.otus, but you can do this instead.

mothur > get.groups(list=yourListFile, groups=negativeControlSampleName) - create a list file containing only the OTUs with reads from negativeControlSampleName

mothur > list.otus(list=current) - create accnos file containing names of OTUs containing reads from negativeControlSampleName

mothur > remove.otus(list=yourListFile, accnos=current) - remove OTUs containing reads from negativeControlSampleName from your original list file

**Comment by miragr** [comment]
Great! Now it works! I also did similar procedure for count file using remove.seqs and then I was able to proceed to making shared file. Many thanks for your help!
