### ISSUE TITLE
Question on: Workshops

### ISSUE THREAD

**Issue by nikaalina** [mothur/mothur.github.io#44]
Hi, my name's Nika from Indonesia. Currently, I begin studying the coral microbiome and need to learn about Mothur as an analysis tool. Unfortunately, I missed the workshop which is would be very useful for my study. Can I have the record or something to enrich me about this topic?

**Comment by pschloss** [comment]
Hi Nika,

Thanks for your interest. Scheduling the next workshop is still in the works. If you have signed up for the mailing list through mothur.org you'll be among the first to hear about it.

Pat
