### ISSUE TITLE
pcr.seqs

### ISSUE THREAD

**Issue by aganve** [mothur/mothur.github.io#45]
Hello,
Can I use the pcr.seqs command to isolate my PCR insert from the plasmid vector? I see that it has the option to trim up to a certain point and trim from a certain point. Can I use pcr.seqs to accomplish this? And will it output my trimmed fasta sequences? 

Thanks.

**Comment by pschloss** [comment]
Hi - you should be able to do that, but there are probably tools better designed for working with plasmids and cloning products.

Pat
