### ISSUE TITLE
align.seqs

### ISSUE THREAD

**Issue by merryblues** [mothur/mothur.github.io#48]
Hello, I have a question, I have to align my data with the greengene database but I get this error  "template is not aligned, aborting", could you please help me, I don't know what I'm doing wrong.
align.seqs(fasta=stability.trim.contigs.good.unique.fasta, reference=gg_13_8_99.fasta, processors=4)

align.seqs

**Comment by pschloss** [comment]
That reference is not aligned, it is used for classification. I'd strongly recommend using one of the SILVA reference alignments that we have on the wiki. The greengenes reference alignment is pretty horrible. It's ok for classification, but not alignment.
