### ISSUE TITLE
Update Mothur in Ubuntu

### ISSUE THREAD

**Issue by RAnytime** [mothur/mothur.github.io#50]
Dear All, I've installed Mothur 1.42.1 on Ubuntu 20... Now I tried to update to 1.44.3. After unzipping the folder from Your page and copying the files to the old installation folders I always get the old version. In the mean time I suppose that the Mothur's Ubuntu version wasn't updated to 1.44.3? Or is there any secret? Belive me, I've uninstalled and manually removed Mothur 1.42.1 several times...
Thanks a lot in advance for any help!

**Comment by mothur-westcott** [comment]
I just downloaded and installed this, https://github.com/mothur/mothur/releases/download/v1.44.3/Mothur.linux_noReadline.zip, and ran the following:

./mothur --version

Linux
Mothur version=1.44.3
Release Date=8/27/20
