### ISSUE TITLE
make.contigs help

### ISSUE THREAD

**Issue by dschnitzler14** [mothur/mothur.github.io#51]
I am very new so I don't know if this is an issue or just me being clueless.

I am trying to run make.contigs but just get lines and lines of Warning messages and no group/count output. I have the pairs fastq.gz files that I have trimmed using cutadapt in the mothur folder. So for example I have my pairs as "trimmed_BP1_1.fastq.gz" and "trimmed_BP1_2.fastq.gz". I then used `make.file` to make the stability.files (which seems to have worked).

I then run `make.contigs(file=stability.files, processors=8)` but just get lines and lines of this (example except):

```
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, M05898_65_000000000-CC66F_1_1114_13609_28642.
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, M05898_65_000000000-CC66F_1_1114_13676_28685.
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, M05898_65_000000000-CC66F_1_1114_15309_28704.
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, M05898_65_000000000-CC66F_1_1114_18097_28723.
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, M05898_65_000000000-CC66F_1_1114_18186_28772.
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, M05898_65_000000000-CC66F_1_1114_18909_28809.
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, M05898_65_000000000-CC66F_1_1114_16906_28850.
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, M05898_65_000000000-CC66F_1_1114_17719_28857.
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, M05898_65_000000000-CC66F_1_1114_15438_28866
```

What am I doing wrong? Do the files need to live somewhere else?

Edit: I am running mothur v.1.44.3

**Comment by mothur-westcott** [comment]
This error indicates you are missing reads from one of the fastq files. If you send your input files to mothur.bugs@gmail.com I will take a closer look for you.
