### ISSUE TITLE
Question on: version 1.39.5 and 1.44.3

### ISSUE THREAD

**Issue by XiaowuBioinformatics** [mothur/mothur.github.io#55]
Hi All,

I use the same data and process the analysis with versions 1.39.5 and 1.44.3 using the same command. I found the "uchime.chimera" step generates very different output regarding the sequences screened. Version 1.39.5 removes much more chimeric sequences. I note that the versions after 1.39.5 have updated or fixed so-called bugs about the uchime.chimera. It seems like to be that version 1.44.3 detects fewer chimeric sequences in comparison with that of version 1.39.5. Which version should I go for? Greatly appreciated it if anyone can help with it. Thank you very much.

**Comment by mothur-westcott** [comment]
I recommend upgrading to version 1.45.0, https://github.com/mothur/mothur/releases/tag/v.1.45.0.

**Comment by XiaowuBioinformatics** [comment]
> I recommend upgrading to version 1.45.0, https://github.com/mothur/mothur/releases/tag/v.1.45.0.

Hi Sir. Thank you very much for your prompt reply. About version 1.45.0, it is impracticable to copy and paste the command code, which is not convenient. This is the reason for playing with 1.44.3. It would be perfect if your team can improve it.  

Again, would you please suggest that which is correct for the step of uchime.chimera, version 1.39.5 or 1.44.3? They produced very different results with the same input file. Looking forward to your reply.

**Comment by mothur-westcott** [comment]
The 1.44.3 version contained an error in the assembly of the accnos file which resulted in some chimeras not being removed. It is corrected in our latest version. Version 1.39.5 and version 1.45.1 produce similar results. My recommendation is to upgrade to our latest version, https://github.com/mothur/mothur/releases/tag/v1.45.1.
