### ISSUE TITLE
Question on: Silva reference files

### ISSUE THREAD

**Issue by jianshu93** [mothur/mothur.github.io#57]
Why not include archaea but only bacteria in the 132 reference database?

16S analysis will always capture archaea 16S.

Jianshu

**Comment by pschloss** [comment]
The [v132 reference](https://mothur.org/wiki/silva_reference_files/) does include Archaea. Are you not seeing it there?

> Full-length sequences and taxonomy references (188247 bacteria, 4626 archaea, and 20246 eukarya sequences). This reference could be customized for alignments, but could also be used for classification. The uncompressed version is ~9.9 GB and the compressed version is 348 MB.

Pat

**Comment by jianshu93** [comment]
I mean the bacteria alone alignment file you provided. archaea should also be provided because common primer will always capture archaea. users just do not want to run a second time for archaea. I am talking about this because the full alignment from silva includes 18S and the file is huge.
