### ISSUE TITLE
Question on: unique.seqs

### ISSUE THREAD

**Issue by dungtran2612** [mothur/mothur.github.io#59]
Hi, 
I have a total of 14430026 sequences after screen.seq. But after unique.seq, there is only 618,368 unique sequences. Is it normal when I have around 4% unique sequences?
It is soil, rhizosphere and root samples and I used V4.
Thank you,
Dung

**Comment by pschloss** [comment]
That seems reasonable.

**Comment by dungtran2612** [comment]
Thank you, Dr. Schloss.
After finishing all commands in your SOP, I have a total of 202,238 sequences. The chimera step removed 25% of my data. I used chimera.uchime command. In your SOP, you mentioned 8% is a reasonable using vsearch. Is it normal 25% of data to be flagged as chimeric?
Thank you.

**Comment by pschloss** [comment]
We sometimes see up to 25 or 30% of all sequences being flagged as chimeric. If you have questions about the pipeline, I’d encourage you to post them to the forum.

THanks,
Pat
