### ISSUE TITLE
count.seqs turns off Mothur

### ISSUE THREAD

**Issue by Cesar2112** [mothur/mothur.github.io#61]
Hi friends,
while running SOP, I wish to generate count_table:

> count.seqs(name=Allfasta.good.names, group=Allgroups.good.groups)

Mothur suddenly turns out without giving any clues about the problem. 
so, I'm forced to quit the program. ☹
It's being Four times I try with the same problem
Any idea?
Thanks in advance,
César

**Comment by mothur-westcott** [comment]
Could you send your name and group file to mothur.bugs@gmail.com so I can track down the issue for you?

**Comment by Cesar2112** [comment]
Thanks Sarah, I just send the email. 
Have a nice day
