### ISSUE TITLE
Question on: mothur's blog

### ISSUE THREAD

**Issue by christellesawaya** [mothur/mothur.github.io#62]
Hi, I have FQ format files I want to analyze on mothur. How can I convert the files to FASTQ format? 
The FQ format is on read on mothur application.
Thank you

**Comment by pschloss** [comment]
I'm not sure what FQ format is, but I'd assume it's fastq. You should be able to use that directly in make.contigs.  It would be easiest to keep track of questions if you could post future queries at forum.mothur.org
