### ISSUE TITLE
Question on: taxonomy file

### ISSUE THREAD

**Issue by hannah-doris** [mothur/mothur.github.io#63]
I have made my own taxonomy file and am trying to do my own classify.seqs on mothur. I keep getting an error:

'CSMB|5300' is in your template file and is not in your taxonomy file. Please correct.
'CSMB|5301' is in your template file and is not in your taxonomy file. Please correct.
'CSMB|5302' is in your template file and is not in your taxonomy file. Please correct.
'CSMB|5303' is in your template file and is not in your taxonomy file. Please correct.
'CSMB|5304' is in your template file and is not in your taxonomy file. Please correct.
'CSMB|5305' is in your template file and is not in your taxonomy file. Please correct.
DONE.

I get this error for every single CSMB| 1-5305. I am attaching one of the taxonomy and reference files that I have created. Although, these file formats are in .txt so that I could attach them but they are actually in .tax and .fa when I submit them in the command. Here is an example of the command I am submitting:

classify.seqs(fasta=current, name=current, group=current, reference=CSMB_test_seq.fa, taxonomy=CSMB_test_tax.tax, cutoff=80)

I am wondering what am I doing wrong with the formatting of the taxonomy and/or reference file? Any advice would be greatly appreciated. Thanks!

[CSMB_test_seq.txt](https://github.com/mothur/mothur.github.io/files/7108944/CSMB_test_seq.txt)
[CSMB_test_tax.txt](https://github.com/mothur/mothur.github.io/files/7108945/CSMB_test_tax.txt)

**Comment by mothur-westcott** [comment]
I ran classify.seqs with your reference files using our latest version, https://github.com/mothur/mothur/releases/tag/v1.46.1, and did not receive an error. Are you using our current version?

**Comment by EllistonV** [comment]
I also have a similar problem, and I am using the latest version. Any advice on this?
