### ISSUE TITLE
Question on: screen.seqs

### ISSUE THREAD

**Issue by JoeHansen4444** [mothur/mothur.github.io#65]
My alignment file has 508862 sequences, but I am trying to eliminate the sequences that are not aligned. 
 Start   End     NBases  Ambigs  Polymer NumSeqs
Minimum:        0       0       0       0       1       1
2.5%-tile:      1044    1044    1       0       1       12722
25%-tile:       10369   25316   6       0       1       127216
Median:         43029   43116   12      0       3       254432
75%-tile:       43097   43116   28      0       3       381647
97.5%-tile:     43113   43116   64      0       6       496141
Maximum:        43116   43116   517     2       46      508862
Mean:   32520   32845   20      0       2
# of Seqs:      508862

I set the end based on the example, but too many sequences were removed:
mothur > screen.seqs(fasta=C:\mothur\Dolphin\DolphinSamplesCat_1.align, end=43000)
It took 1550 secs to screen 508862 sequences, removed 202736.
Output File Names:
C:\mothur\Dolphin\DolphinSamplesCat_1.good.align
C:\mothur\Dolphin\DolphinSamplesCat_1.bad.accnos

There should have only been closer to 139938 sequences removed. Also when I did summary.seqs for the good align there were only 204028 sequences: 

mothur > summary.seqs(fasta=C:\mothur\Dolphin\DolphinSamplesCat_1.good.align)

Using 8 processors.

                Start   End     NBases  Ambigs  Polymer NumSeqs
Minimum:        41534   43061   10      0       1       1
2.5%-tile:      42970   43116   10      0       2       5101
25%-tile:       43017   43116   13      0       3       51008
Median:         43029   43116   22      0       3       102015
75%-tile:       43059   43116   28      0       6       153022
97.5%-tile:     43097   43116   40      0       6       198928
Maximum:        43101   43116   110     2       38      204028
Mean:   43032   43115   21      0       3
# of Seqs:      204028

This means there are 102098 sequences that are not in the file and were not removed by the screen. I am not sure why this is happening and would appreciate any help.

**Comment by mothur-westcott** [comment]
The summary data indicates you have poor overlap and low number of bases. What region are you sequencing? 

The screen.seqs command below will remove all sequences that end before position 43000. 

mothur > screen.seqs(fasta=C:\mothur\Dolphin\DolphinSamplesCat_1.align, end=43000)

**Comment by JoeHansen4444** [comment]
We conducted 16s sequencing looking at the v3 and v4 regions.

**Comment by JoeHansen4444** [comment]
I will read through this. Thank you for the help.
