### ISSUE TITLE
Question on: Customize your reference alignment for your favorite region

### ISSUE THREAD

**Issue by BeccaEvans-soil** [mothur/mothur.github.io#71]
Hi Pat, 

I attended your workshop on Mothur in September 2021. I got my amplicon data back and I am working on creating a reference alignment for the v6 v8 region. I worked through the protocol 

mothur > pcr.seqs(fasta=ecoli.fasta, oligos=PCR_oligos.txt)

my PCR_oligos file looks like: 
forward ACGCGHNRAACCTTACC
reverse TTGYACSCACYGCCCGT

#but when I get to this step mothur says  that ecoli.pcr.fasta is blank, even though it is not when I open it in atom so I cannot align
mothur <align.seqs(fasta=ecoli.pcr.fasta, reference=silva.bacteria.fasta)

Do you have any suggestions?
Thanks
Becca

**Comment by pschloss** [comment]
Sometimes the easiest approach is to manually look for the primers. I was able to find the forward primer, but the reverse primer was not included in the reverse compliment as mothur expected. Also the reverse primer seems to have a mismatch:

```
>E.coli
ACGCGHNRAACCTTACC <-forward primer
ACGCGAAGAACCTTACCTGGTCTTGACATCCACGGAAGTTTTCAGAGATGAGAATGTGCCTTCGGGAACCGTGAGACAGG
TGCTGCATGGCTGTCGTCAGCTCGTGTTGTGAAATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTATCCTTTGTTGC
CAGCGGTCCGGCCGGGAACTCAAAGGAGACTGCCAGTGATAAACTGGAGGAAGGTGGGGATGACGTCAAGTCATCATGGC
CCTTACGACCAGGGCTACACACGTGCTACAATGGCGCATACAAAGAGAAGCGACCTCGCGAGAGCAAGCGGACCTCATAA
AGTGCGTCGTAGTCCGGATTGGAGTCTGCAACTCGACTCCATGAAGTCGGAATCGCTAGTAATCGTGGATCAGAATGCCA
CGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGT
                     TTGYACSCACYGCCCGT <- reverse primer
```

[IUPAC degenerate codes](https://www.bioinformatics.org/sms/iupac.html):
H: ACT
N: ATGC
R: AG
Y: CT
S: GC

To use the oligos file, you'd insert the reverse primer using the reverse compliment (i.e. use the sequence you ordered from the company that synthesized the oligos). You'll notice that the primer has a `S`, which matches a `G` or `C`, but in that slot of the E. coli sequence there is an `A`.
