### ISSUE TITLE
Question on: mothur's blog

### ISSUE THREAD

**Issue by Sithara85** [mothur/mothur.github.io#91]
Hi Pat,

I have a quick question about Miseq SOP, after screen.seqs we will get a good.fasta and good.count_table files. So in the following step using unique.seqs shouldn't we be using these files instead of unique.seqs(fasta=stability.trim.contigs.fasta, count=stability.contigs.count_table) as in below?

unique.seqs(fasta=stability.trim.contigs.good.fasta, count=stability.contigs.good.count_table)

Thank you,
Sithara

**Comment by pschloss** [comment]
Correct
