### ISSUE TITLE
Mothur

### ISSUE THREAD

**Issue by Blueiris12** [mothur/mothur.github.io#93]
Mothur 
In screen.seqs, how to determine maxambig, maxlength, minlength

**Comment by pschloss** [comment]
maxambig should always be zero. For max and min length you need to know
something about the distribution of lengths for good sequences in your
region. I still strongly plea with people to use V4 and the values on the
SOP but if you aren’t using V4 you can use
https://mothur.org/blog/2016/Customization-for-your-region/ to find the
right region and then process the Silva reference alignment to get the
right numbers. Maybe give 5 extra nucleotides on both ends

Pat
