### ISSUE TITLE
Mothur question on V3/V4 region

### ISSUE THREAD

**Issue by mothur07** [mothur/mothur.github.io#95]
I am analyzing V3/V4 region. I am new to mothur and I had some basic queries. I have 8gb RAM, mothur version = 1.42.1, ubuntu 20.o4
1. In first scree.seqs result how to determine maxambig, minlegth, maxlength and maxhomop
2. In second scree.seqs how to determine start and end points
3. how reference file for V3/V4 region from silva.bacteria.fasta
4. pre.cluster is giving segmentation fault, how to deal with this. 
![Screenshot from 2022-09-28 16-44-49](https://user-images.githubusercontent.com/114558765/192765840-4d4a501a-83e1-4ed9-bfae-4a9f2a20c783.png)

**Comment by pschloss** [comment]
FWIW, I strongly discourage using regions that are not V4 for reasons outlined [here](https://mothur.org/blog/2014/Why-such-a-large-distance-matrix/). If you are using another region, you need to generate a [customized reference alignment](https://mothur.org/blog/2016/Customization-for-your-region/). Once you generate that alignment, you'll want to run it through `summary.seqs` to get the expected length distributions. The value for `maxambig` should always be zero.

We are now on [v1.48 of mothur](https://github.com/mothur/mothur/releases/tag/v1.48.0). The version you are using is a few years old and will not have the same features as this version.

**Comment by LeeJH5120** [comment]
In first scree.seqs result how to determine maxambig, minlegth, maxlength and maxhomop
In second scree.seqs how to determine start and end points

after primer seq trmming 
maxambig=1,minlength=$Minlength, maxlength=$Maxlength, maxhomop=NR


how reference file for V3/V4 region from silva.bacteria.fasta
https://mothur.s3.us-east-2.amazonaws.com/wiki/silva.nr_v132.tgz
(16s rRNA full length of bacteria)

pre.cluster is giving segmentation fault, how to deal with this.
1/100nt ( i.e : v3-v4 > 400nt  diff=4 )

**Comment by pschloss** [comment]
Please post this question to forum.mothur.org
