### ISSUE TITLE
Question on: MiSeq SOP

### ISSUE THREAD

**Issue by Yaping361** [mothur/mothur.github.io#97]
pre.cluster(fasta=stability.trim.contigs.good.unique.good.filter.unique.fasta, count=stability.trim.contigs.good.unique.good.filter.count_table,diffs=4)。When I used this code , Pre.cluster removed all sequences.
![图片](https://user-images.githubusercontent.com/72778215/196601697-a37961db-9473-4ff6-b5f6-3c46dbd9eb2d.png)。Why is this?

**Comment by pschloss** [comment]
Please ask questions about the use of mothur at the forum - https://forum.mothur.org/
