### ISSUE TITLE
Question on: make.contigs

### ISSUE THREAD

**Issue by christellesawaya** [mothur/mothur.github.io#98]
Hi, 
I am using a high performance computer to analyze V3-V4 sequences using mothur v.1.46.1 that is available. when running the make.contigs command, the output files are:
stability.scrap.contigs.fasta
stability.trim.contigs.fasta
stability.contigs.report
stability.contigs.groups

Following this, I am not able to proceed with the SOP because no count_table file was generated
Then, using the group file generated instead, mothur is unable to open any file even after trying to reset the directory

Is the problem in the directory?

**Comment by pschloss** [comment]
It looks like you're using an old version of mothur. We changed the output
files from make.contigs after 1.46. I'd encourage you to install the most
recent version of mothur.

Pat

**Comment by christellesawaya** [comment]
Thank you for the reply. 
I was able to generate the required file using the latest version.
The second problem I am facing is that the sequencing targeted the V3-V4 region with customizable primers. 
If I am only interested in the V4 region and run the same coordinates suggested in the SOP for that region, this generated mismatch:
"[WARNING]: 10690 of your sequences generated alignments that eliminated too many bases, a list is provided in stability.trim.contigs.good.unique.flip.accnos.
[NOTE]: 4710 of your sequences were reversed to produce a better alignment."
and then, the outputs generated don't match to proceed with the summary command.

Generally, is it possible to target the V4 region even when V3-V4 region was targeted?

**Comment by pschloss** [comment]
Hi -- that is just a warning. If your reference alignment only has the V4
region then when you aling V3-V4 against it, it will remove many bases
(i.e., those from the V3 region). You should be fine to keep going with the
next step

**Comment by christellesawaya** [comment]
Thank you for the tip. After running the screening and targeting the V4 region only,  I couldn't generate a summary because my fasta and count table files don't match.
Is it a problem with the V4 region targeted? (I used start=1968, end=11550)

**Comment by pschloss** [comment]
Make sure that you include the count file in screen.seqs. If you're getting
things to not match, I'd go back enough steps until they do and then go
forward making sure htat you have the right files at each step

Pat
