### ISSUE TITLE
Question on: fastq.info

### ISSUE THREAD

**Issue by msolbach** [mothur/mothur.github.io#99]
Dear mothur team,
I am currently trying to run the fastq.info command to parse sequences from 2 fastq files (forward and reverse run from Illumina miSeq) using an oligos file. Usually, I would use the make.contigs command with subsequent filtering, however, a colleague wants to have the sequences demultiplexed, but not assembled to contigs. Therefore, fastq.info seems to be the appropriate command. It should search for the barcodes + primers from the oligos file, and split the fastq files into a forward and reverse file for each sample in the oligos file.

This is what I am trying to do:
fastq.info(file=File.txt, oligos=Oligosheet.txt, checkorient=T, fasta=F, qfile=F)
The File.txt contains only one row, with 2 columns (the names of the two fastq files): Drought_R1.fastq	Drought_R2.fastq
The command runs smoothly without any error messages. However, 99% (or so) of the reads are sorted into scrap.forward.fastq and scrap.reverse.fastq files (almost as big as the original fastq files). Only a tiny, tiny amount of reads is recognized to belong to a sample (Group count: B4A22_D 20, Total of all groups is 20; and parsed files are only built for B4A22_D, accordingly). Note that sample B4A22_D happens to be the first one in my oligos file (see below).

Also, when checking the sequences of that one sample (B4A22_D), it seems like the barcodes are removed by the fastq.info command, but not the primers? Is that how it is supposed to be? make.contigs clips both, doesn't it?

Here is the head of my oligos file (the same oligos file works perfectly fine with make.contigs):
Primer	GTTAAAARGCTCGTAGTYG	AAGARGAYATCCTTGGTG	
barcode	GTGAACTC	ACGATCAG	B4A22_D
barcode	GTGAACTC	CGTTCAAG	B3A09_R
barcode	GTGAACTC	ATTCTCGG	B3A02_D
barcode	GTGAACTC	TCTCTCAG	B3A02_R
...

So I am wondering now if anything with my input parameters or files is wrong, or if there is a weird bug happening. As mentioned before, make.contigs works just fine, resulting in 13 Million contigs (Total of all groups is 13013691) using the exact same input files. I did not find any helpful information online yet, and I am really sorry if I am just being stupid here, but I have the impression that something does not quite work here with fastq.info. Thanks to everyone for their help!

I am using mothur v.1.45.3 (but according to the Wiki there has only been one change to the command since this version that should not really affect the issue here).

Thanks so much, and all the best,
Marcel

**Comment by msolbach** [comment]
Hello again,
sorry for being a bit annoying, but just a quick heads up that I still haven't figured out how to solve the problem.
Also, I noticed that the default for "format" is set to "sanger" for fastq.info, and to "illumina1.8+" for make.contigs. I thought that maybe a wrong quality-score format was my issue, but sadly that does not seem to be the case.
I would really like to sort this out somehow! If you need any additional information or files, please let me know!

Best,
Marcel

**Comment by pschloss** [comment]
Hi Marcel - What you're trying to do isn't really how we intended to create these commands. When we use the oligos option mothur generally expects the sequences to start and end with the listed primers and barcodes. So if one of them is missing, it will go to the scrap file. This seems to be what you are seeing. If your colleague really wants demultiplexed but not assembled here's what I would suggest...

1. Run `make.contigs` to generate a group file (the older version of mothur will make a group file, this is now replaced with a count_file)
2. Use bash/R/something to put the names of sequences into separate files - one file per group - that only has the sequence name on each line. Call this an accnos file
3. Run `fastq.info` to get the fasta sequences (and qual scores) out of each fastq file
4. Run `get.seqs` with each accnos file on both fastq files. You will need to change the name of each file after it is generated so they don't write over each other.

Again, mothur really wasn't written to do what you all want. I'm not sure why they want separate fasta files for each read and sample. The quality scores are very important to assembly and trimming sequences prior to assembly results in worse assemblies.

Good luck,
pat

**Comment by msolbach** [comment]
Dear Pat,
thank you very much for you reply and help! So, if I understand correctly, the command cannot be used the way I have in mind, because the fastq files only contain one of the barcodes and primers each, right? Since the sequences are not assembled yet, they will always only contain a forward barcode+primer, or a reverse barcode+primer, but not both. So mothur will sort them into the scrap file.
Then I am a bit confused why the command accepts paired fastq files and an oligos file as input if the command will not be able to work with these files anyways.

Thank you very much for the suggestion! This seems a bit tedious, but should work! The only thing that I still need to do then is to trim the barcodes and primers. But I will try, thank you!

Well, the colleagues are usually using a different pipeline with standard bacteria primers, if I am not mistaken. I am not sure what software or pipeline they use exactly, but it looks like it cannot deal with the taxon-specific custom primers that we were using in our approach. They are asking for demultiplexed but not assembled sequences because it corresponds to their usual approach and should be compatible with their pipeline.
